config/routes.rb
Rails.application.routes.draw do
  resources :tasks
  root to: 'index#index'
  resources :journal_entries
  resources :journals
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/journal.rb
class Journal < ApplicationRecord
  has_many :journal_entries, dependent: :destroy

  def journal_entries_by_collection
    tasks = []
    jes_by_collection = ActiveSupport::OrderedHash.new { |h, k| h[k] = [] }
    jes = self.journal_entries.order(:created_at)
    jes.each do |je|
      d_str = "#{je.created_at.month}-#{je.created_at.day}-#{je.created_at.year}"
      jes_by_collection[d_str] << je
      if je.in_collection?
        jes_by_collection[je.collection] << je
      end

      if je.is_task?
        tasks << je
      end
    end

    jes_by_collection[Time.now.strftime('%-m-%-d-%Y')].insert(0, *tasks)

    return jes_by_collection
  end
end

app/models/journal_entry.rb
class JournalEntry < ApplicationRecord
  belongs_to :journal
  has_one :task, dependent: :destroy
  attribute :created_at_js, :string

  def in_collection?
    return !self.collection.to_s.strip.empty?
  end

  def is_task?
    return !self.task.nil?
  end

  def created_at_js
    return self.created_at.strftime('%Y-%m-%d %H:%M:%S.%3N')
  end
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :journal_entry

  def self.new_default_from_journal_entry(journal_entry)
    task = Task.new(
      journal_entry: journal_entry,
    )

    if !task.save
      raise "Could not save default new task for JournalEntry. You hecked up bad."
    end

    return task
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  def index
  end
end

app/controllers/journal_entries_controller.rb
class JournalEntriesController < ApplicationController
  before_action :set_journal_entry, only: [:show, :edit, :update, :destroy]

  # GET /journal_entries
  # GET /journal_entries.json
  def index
    @journal_entries = JournalEntry.all
  end

  # GET /journal_entries/1
  # GET /journal_entries/1.json
  def show
  end

  # GET /journal_entries/new
  def new
    @journal_entry = JournalEntry.new
  end

  # GET /journal_entries/1/edit
  def edit
  end

  # POST /journal_entries
  # POST /journal_entries.json
  def create
    @journal_entry = JournalEntry.new(journal_entry_params)

    respond_to do |format|
      if @journal_entry.save
        if extension_params[:is_task] == "true"
          Task.new_default_from_journal_entry(@journal_entry)
        end

        format.html { redirect_to @journal_entry, notice: 'Journal entry was successfully created.' }
        format.json { render :show, status: :created, location: @journal_entry }
        format.js { render :show }
      else
        format.html { render :new }
        format.json { render json: @journal_entry.errors, status: :unprocessable_entity }
        # TODO: care about this
        # format.js { render :show }
      end
    end
  end

  # PATCH/PUT /journal_entries/1
  # PATCH/PUT /journal_entries/1.json
  def update
    respond_to do |format|
      if @journal_entry.update(journal_entry_params)
        if extension_params[:is_task] == "true" && !@journal_entry.is_task?
          Task.new_default_from_journal_entry(@journal_entry)
        elsif extension_params[:is_task] == "false" && @journal_entry.is_task?
          @journal_entry.task.destroy
        end

        format.html { redirect_to @journal_entry, notice: 'Journal entry was successfully updated.' }
        format.json { render :show, status: :ok, location: @journal_entry }
      else
        format.html { render :edit }
        format.json { render json: @journal_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /journal_entries/1
  # DELETE /journal_entries/1.json
  def destroy
    @journal_entry.destroy
    respond_to do |format|
      format.html { redirect_to journal_entries_url, notice: 'Journal entry was successfully destroyed.' }
      format.json { head :no_content }
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_journal_entry
      @journal_entry = JournalEntry.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def journal_entry_params
      params.require(:journal_entry).permit(:journal_id, :text, :collection)
    end

    def extension_params
      params.require(:journal_entry).permit(:is_task)
    end
end

app/controllers/journals_controller.rb
class JournalsController < ApplicationController
  before_action :set_journal, only: [:show, :edit, :update, :destroy]

  # GET /journals
  # GET /journals.json
  def index
    @journals = Journal.all
  end

  # GET /journals/1
  # GET /journals/1.json
  def show
  end

  # GET /journals/new
  def new
    @journal = Journal.new
  end

  # GET /journals/1/edit
  def edit
  end

  # POST /journals
  # POST /journals.json
  def create
    @journal = Journal.new(journal_params)

    respond_to do |format|
      if @journal.save
        format.html { redirect_to @journal, notice: 'Journal was successfully created.' }
        format.json { render :show, status: :created, location: @journal }
      else
        format.html { render :new }
        format.json { render json: @journal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /journals/1
  # PATCH/PUT /journals/1.json
  def update
    respond_to do |format|
      if @journal.update(journal_params)
        format.html { redirect_to @journal, notice: 'Journal was successfully updated.' }
        format.json { render :show, status: :ok, location: @journal }
      else
        format.html { render :edit }
        format.json { render json: @journal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /journals/1
  # DELETE /journals/1.json
  def destroy
    @journal.destroy
    respond_to do |format|
      format.html { redirect_to journals_url, notice: 'Journal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_journal
      @journal = Journal.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def journal_params
      params.require(:journal).permit(:name)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def task_params
      params.require(:task).permit(:journal_entry_id, :is_complete)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/journal_entries_helper.rb
module JournalEntriesHelper
end

app/helpers/journals_helper.rb
module JournalsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/index/index.html.erb
<h1>Index#index</h1>
<p>Find me in app/views/index/index.html.erb</p>

app/views/journal_entries/_form.html.erb
<%= form_with(model: journal_entry, local: true) do |form| %>
  <% if journal_entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(journal_entry.errors.count, "error") %> prohibited this journal_entry from being saved:</h2>

      <ul>
        <% journal_entry.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :journal_id %>
    <%= form.number_field :journal_id %>
  </div>

  <div class="field">
    <%= form.label :collection %>
    <%= form.text_field :collection %>
  </div>

  <div class="field">
    <%= form.label :is_task %>
    <%= form.check_box :is_task %>
  </div>

  <div class="field">
    <%= form.label :text %>
    <%= form.text_field :text %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/journal_entries/_single.html.erb
<li class="journal-entry-<%= journal_entry.id %><%= journal_entry.in_collection? ? ' text-muted' : ''%>">
  <%= journal_entry.text %>
  <%= link_to 'edit', edit_journal_entry_path(journal_entry) %>
  <%= link_to 'delete', journal_entry, method: :delete, remote: true %>
</li>

app/views/journal_entries/destroy.js.erb
$(".journal-entry-<%= @journal_entry.id %>").remove()

app/views/journal_entries/edit.html.erb
<h1>Editing Journal Entry</h1>

<%= render 'form', journal_entry: @journal_entry %>

<%= link_to 'Show', @journal_entry %> |
<%= link_to 'Back', journal_entries_path %> |
<%= link_to 'Back to journal', @journal_entry.journal %>

app/views/journal_entries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Journal Entries</h1>

<table>
  <thead>
    <tr>
      <th>Journal</th>
      <th>Text</th>
      <th>Collection</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @journal_entries.each do |journal_entry| %>
      <tr>
        <td><%= journal_entry.journal_id %></td>
        <td><%= journal_entry.text %></td>
        <td><%= journal_entry.collection %></td>
        <td><%= link_to 'Show', journal_entry %></td>
        <td><%= link_to 'Edit', edit_journal_entry_path(journal_entry) %></td>
        <td><%= link_to 'Destroy', journal_entry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Journal Entry', new_journal_entry_path %>

app/views/journal_entries/new.html.erb
<h1>New Journal Entry</h1>

<%= render 'form', journal_entry: @journal_entry %>

<%= link_to 'Back', journal_entries_path %>

app/views/journal_entries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Journal:</strong>
  <%= @journal_entry.journal_id %>
</p>

<p>
  <strong>Text:</strong>
  <%= @journal_entry.text %>
</p>

<p>
  <strong>Collection:</strong>
  <%= @journal_entry.collection %>
</p>

<%= link_to 'Edit', edit_journal_entry_path(@journal_entry) %> |
<%= link_to 'Back', journal_entries_path %> |
<%= link_to 'Back to journal', @journal_entry.journal %>

app/views/journal_entries/show.js.erb
$("#journal-entries-<%= @journal_entry.created_at.strftime('%-m-%-d-%Y') %>")
  .append("<%= escape_javascript render(:partial => 'journal_entries/single', :locals => { :journal_entry => @journal_entry }) %>")
  
$("#journal_entry_text").val('')

app/views/journals/_form.html.erb
<%= form_with(model: journal, local: true) do |form| %>
  <% if journal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(journal.errors.count, "error") %> prohibited this journal from being saved:</h2>

      <ul>
        <% journal.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/journals/_journal_entry_form.html.erb
<%= form_with(model: journal_entry, remote: true) do |form| %>
  <% if journal_entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(journal_entry.errors.count, "error") %> prohibited this journal_entry from being saved:</h2>

      <ul>
        <% journal_entry.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :journal_id %>
    <%= form.hidden_field :journal_id %>
  </div>

  <div class="field">
    <%= form.label :collection %>
    <%= form.text_field :collection %>
  </div>

  <div class="field">
    <%= form.label :is_task %>
    <%= form.check_box :is_task %>
  </div>

  <div class="field">
    <%= form.label :text %>
    <%= form.text_field :text %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/journals/edit.html.erb
<h1>Editing Journal</h1>

<%= render 'form', journal: @journal %>

<%= link_to 'Show', @journal %> |
<%= link_to 'Back', journals_path %>

app/views/journals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Journals</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @journals.each do |journal| %>
      <tr>
        <td><%= journal.name %></td>
        <td><%= link_to 'Show', journal %></td>
        <td><%= link_to 'Edit', edit_journal_path(journal) %></td>
        <td><%= link_to 'Destroy', journal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Journal', new_journal_path %>

app/views/journals/new.html.erb
<h1>New Journal</h1>

<%= render 'form', journal: @journal %>

<%= link_to 'Back', journals_path %>

app/views/journals/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_journal_path(@journal) %> |
<%= link_to 'Back', journals_path %>

<%= react_component(
  "JournalApp",
  {
    name: @journal.name,
    journalEntries: @journal.journal_entries,
  }
) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EquipJournal</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model: task, local: true) do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
        <% task.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :journal_entry_id %>
    <%= form.number_field :journal_entry_id %>
  </div>

  <div class="field">
    <%= form.label :is_complete %>
    <%= form.check_box :is_complete %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tasks</h1>

<table>
  <thead>
    <tr>
      <th>Journal entry</th>
      <th>Is complete</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.journal_entry_id %></td>
        <td><%= task.is_complete %></td>
        <td><%= link_to 'Show', task %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task', new_task_path %>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Journal entry:</strong>
  <%= @task.journal_entry_id %>
</p>

<p>
  <strong>Is complete:</strong>
  <%= @task.is_complete %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>